### ISSUE TITLE
Clean up DbObject and DbService

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive#127]
- [ ] Insert and update are 95% identical. Refactor.
- [x] Properties aren't being used like __use_auditing. Clean up.
- [x] DbObject has a __password for salting with AESencrypt/decrypt. This should be a Config variable, not hard coded in a system file!
- [ ] getDate/Time setDate/Time are redundant (should be marked deprecated) as read/updateConvert do the same thing and theres no need to explicitly have these functions separately. (Found used in Inbox mainly and Tasks)
- [ ] Make function names readable, _tn and _cn are no longer acceptable. We should focus more on maintainability of cmfive and its modules.
- [ ] Pull functionality out where appropriate:
  - Validation should be moved into its own class so it's easily customisable and extensible.
  - Indexing? It could be put into its own module/model/service/whatever where it leverages hooks to maintain its index without clogging up DbObject.
- [ ] Sort out the date functions, maybe create a static date class. There are functions in functions.php but nearly matching functions used in the DbService. This is bad for maintainability. However, making a date class, like config would a) help readability and b) maintainability.
  - i.e. Date::fromTime($time)->output("d-m-Y") for example would leverage PHP's DateTime object to return a formatted string based on a timestamp. It would increase readability as "time2Dt" a) is grammatically incorrect and b) not entirely obvious as to what it does for new users.

One query that I have @careck, is why does DbService maintain transactions and not DbObject, which is responsible for select/insert/update/delete/etc?

**Comment by adam-buckley** [comment]
A good example of validation (Laravel but we can take the concepts) 
http://www.sitepoint.com/data-validation-laravel-right-way/

**Comment by careck** [comment]
__use_auditing is being used by the audit system (which is now using db hooks) ... so please don'r remove!
