### ISSUE TITLE
Access to search rejected when not Admin

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive#129]
It seems, because there are no roles for search, that if you aren't admin, you'll automatically be rejected.

This all handled automatically by cmfive, adding search to anonymous_allowed won't work. Will make a role for it instead.

**Comment by careck** [comment]
is this fixed?

**Comment by adam-buckley** [comment]
Not yet

On Wed, Feb 25, 2015 at 3:28 PM, Carsten Eckelmann <notifications@github.com

**Comment by careck** [comment]
fixed now
