### ISSUE TITLE
date selector difficult selecting year

### ISSUE THREAD

**Issue by syntithenai** [2pisoftware/cmfive#130]
Try entering a birthdate in 1972 Ughh

**Comment by syntithenai** [comment]
maybe lose the JS that prevents typing a date

**Comment by adam-buckley** [comment]
Yeah that or swap the datepicker. There is actually a new datepicker
somewhere in the js source that I wanted to use to replace the existing
solution but making sure it behaves exactly like the current picker (for
legacy) is quite hard to do.

**Comment by adam-buckley** [comment]
Fixed
