### ISSUE TITLE
universal favourites

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive#132]
just like being able to assign universal tags to any object, it would be great if a user could "star" any object and access it via a "favourites list".

This is especially useful for task tracking where you could be overwhelmed with hundreds of tasks, but on a day to day basis only work on a handful.

This is an urgent feature.

**Comment by adam-buckley** [comment]
Would it be appropriate to modify the history item so you could star the
page you're currently on and have a separate display for those pages with
extra UI elements to un-favourite said pages?

We could instead also make a menu item that displays favourited pages in a
list.

On Wed, Feb 25, 2015 at 3:33 PM, Carsten Eckelmann <notifications@github.com

**Comment by careck** [comment]
I like the menu item with a list of favourited pages better

**Comment by careck** [comment]
As my workload increases I really need this feature so that I can mark the projects and individual tasks which I need to monitor. I think the interface should look like this:

1. to mark something as favourite
-> not useful to mark a page a favourite! Rather give the action implementor the option to easily add a button to mark an OBJECT a favourite ... the favourite table would then store the object class, the id and the user id.

2. to display favourites
-> make this a partial and a dashboard widget
-> the display should be full width with a tabbed interface with the different object classes at the top
-> each tab would display a lost of objects using the standard SEARCH methods for displaying
-> this means that if you want an object to be marked as favority you also have to implement the search title etc. functions
-> the favourite display is very similar to a handpicked search list
