### ISSUE TITLE
access to assets 

### ISSUE THREAD

**Issue by syntithenai** [2pisoftware/cmfive#147]
when there is an assets folder inside system/modules/modulename resources like images can be acceed via the URL   /system/modules/modulename/assets/picture.png

when the assets folder is inside the toplevel modules folder, it is not possible to access the image resource by URL.

**Comment by careck** [comment]
Please provide an example URL for an asset in a "toplevel module" folder.

**Comment by syntithenai** [comment]
http://attendance/modules/attendance/assets/myimage.png



On Thu, Jun 18, 2015 at 10:33 AM, Carsten Eckelmann <
notifications@github.com> wrote:

> Please provide an example URL for an asset in a "toplevel module" folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2pisoftware/cmfive/issues/147#issuecomment-112991989>.
>



-- 
Steve Ryan
Software Engineer
stever@syntithenai.com
phone (mobile) 0423 083 685
phone (SIP)  61262237142
skype : irishflute
260 Spring Creek Road Buckajo NSW 2550
Australia

**Comment by careck** [comment]
This used to work and we have a system in production where this works. Please check that there isn't a problem with the url (spelling?) or a config problem with your web server.

**Comment by gcoram1** [comment]
ok,
not sure what I was doing wrong but...
http://fcs-timesheets.gregs/modules/attendance/assets/righttriangle.png
works, and ....
http://fcs-timesheets.gregs/modules/attendance/templates/img/lefttriangle.png
and ...
<img src="modules/attendance/assets/lefttriangle.png">
also works.

any preference ? modules/assets/my.png or module/templates/img/my.png
I like the later as images are normally references from templates but happy
to go with any scheme.


On Thu, Jun 18, 2015 at 10:43 AM, Carsten Eckelmann <
notifications@github.com> wrote:

> This used to work and we have a system in production where this works.
> Please check that there isn't a problem with the url (spelling?) or a
> config problem with your web server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2pisoftware/cmfive/issues/147#issuecomment-112995431>.
>



-- 
---

Greg Coram
0403476757

**Comment by careck** [comment]
I prefer the former with a central asset folder per module, eg.
/modules/attendance/assets/... The templates folder should only contain
template files.

Kind regards,

Carsten Eckelmann
*triple**A**cs*
expert cloud solutions

Mobile 0458 79 55 44
carsten@tripleacs.com
www.tripleacs.com

**Comment by gcoram1** [comment]
<img src="modules/attendance/assets/lefttriangle.png">
it is.

cheers !


On Thu, Jun 18, 2015 at 6:41 PM, Carsten Eckelmann <notifications@github.com
> wrote:

> I prefer the former with a central asset folder per module, eg.
> /modules/attendance/assets/... The templates folder should only contain
> template files.
>
> Kind regards,
>
> Carsten Eckelmann
> *triple**A**cs*
> expert cloud solutions
>
> Mobile 0458 79 55 44
> carsten@tripleacs.com
> www.tripleacs.com
>
> On 18 June 2015 at 18:00, Greg Coram <notifications@github.com> wrote:
>
> > ok,
> > not sure what I was doing wrong but...
> > http://fcs-timesheets.gregs/modules/attendance/assets/righttriangle.png
> > works, and ....
> >
> >
> http://fcs-timesheets.gregs/modules/attendance/templates/img/lefttriangle.png
> > and ...
> > <img src="modules/attendance/assets/lefttriangle.png">
> > also works.
> >
> > any preference ? modules/assets/my.png or module/templates/img/my.png
> > I like the later as images are normally references from templates but
> happy
> > to go with any scheme.
> >
> >
> > On Thu, Jun 18, 2015 at 10:43 AM, Carsten Eckelmann <
> > notifications@github.com> wrote:
> >
> > > This used to work and we have a system in production where this works.
> > > Please check that there isn't a problem with the url (spelling?) or a
> > > config problem with your web server.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/2pisoftware/cmfive/issues/147#issuecomment-112995431
> > >.
> > >
> >
> >
> >
> > --
> > ---
> >
> > Greg Coram
> > 0403476757
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/2pisoftware/cmfive/issues/147#issuecomment-113068033
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2pisoftware/cmfive/issues/147#issuecomment-113078077>.
>



-- 
---

Greg Coram
0403476757
