### ISSUE TITLE
deleting a taskgroup doesn't work

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive#150]
GET /task-group/deletetaskgroup/

responds with:

Notice: Undefined variable: group_details in /home/pi2soft/public_html/cmfive/system/modules/task/task.group.actions.php on line 152

Notice: Trying to get property of non-object in /home/pi2soft/public_html/cmfive/system/modules/task/task.group.actions.php on line 152

Warning: Cannot modify header information - headers already sent by (output started at /home/pi2soft/public_html/cmfive/system/modules/task/task.group.actions.php:152) in /home/pi2soft/public_html/cmfive/system/web.php on line 1464

**Comment by adam-buckley** [comment]
I don't have this issue, is it still a thing?
