### ISSUE TITLE
Add Mandrill API support to MailService

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive#163]
Weird things are happening when sending to mandrillapp via SwiftMailer, adding support for Mandrill's API, bypassing SwiftMailer could help fix any issues.

**Comment by careck** [comment]
please explain what things are happening. We've been using swiftmailer with Mandrill smtp method for over 6 months now without any problems.

**Comment by adam-buckley** [comment]
Use of the Mandrill transport requires the use of SSL and the definition of the certificate file in the php.ini's curl.cainfo
