### ISSUE TITLE
Internationalisation (I18N) of the UI

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive#17]
Be able to present the UI in different languages.
- default language should be set in global config.php
- each user should set his/her own language

**Comment by careck** [comment]
In a recent discussion about cmfive and client applications the subject of I18n was raised again ... so it may become more of a priority this year.

I'm still leaning towards the wordpress (gettext) style. It is also modular like cmfive so each module can come with its own language files. Some things need to be considered, read this article:

http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/

**Comment by syntithenai** [comment]
I've updated the cmfive translations branch to use a gettext approach based on wordpress.
 
I'm thinking this is good to have sorted before the acceptance tests spread much wider.

Awesome tooling available for po files.
- https://poeditor.com/projects/ offering live translation
- or the application http://poedit.net/
- or pootle (which is available as a docker image) for self hosting.


move to gettext based translation implementation
translatable shortcuts WP style _(), _e(),_n(),_en()
per module translations folder containing gettext directory structure
translations preloaded by web for current module
translate example module with online translation https://poeditor.com/projects/    for fr,de,jp,us(fun)
user admin updated to provide language field, default system.language overriden by user language

pull it, update your user language, hit the example module..

**Comment by syntithenai** [comment]
Having talked this stuff through with Carsten
- partials and hooks need to change and reset the domain (which module to use translations from)
- artifax provides business translations to allow changing labels in additional to languages based translation. This could be implemented with gettext too
- the functions.php translation shortcuts should take an extra parameter to explicitly set the domain.
- TODO investigate how wordpress implements the _x shortcut (allowing translation context) which is not available in vanilla gettext
- look into locale based date/currency converstion
- look into language switching - templates, help, automagic model based labels.

**Comment by careck** [comment]
We also discussed that the change of text domain for partials and hooks can be done centrally in Web when the partial or hook is called.

Web::callHook() and Web::partial().

**Comment by careck** [comment]
Also we should be using the double underscore function __()  instead of single underscore _() so that we can add functionality before handing over to gettext (eg. the business translation mentioned above.)

**Comment by adam-buckley** [comment]
I think translations are in place and ready for actual translations. Couldn't get this working on Windows though
