### ISSUE TITLE
Show PDF, ODT, ODS attachments with embedded viewer

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive#176]
Use the library below to embed those attachments directly on the attachments page.

http://viewerjs.org/

**Comment by adam-buckley** [comment]
Usable version on master

**Comment by adam-buckley** [comment]
The implementation is in the Html library, to use it, call
```php
echo Html::embedDocument('/file/atfile/<attachment_id>');
```
Which also allows an option width and height specification of the iframe.
