### ISSUE TITLE
getObject returns incorrect timestamps

### ISSUE THREAD

**Issue by syntithenai** [2pisoftware/cmfive#183]
If I insert a date into the database and query it using unix_timestamp
- getObjects returns the correct timestamp
- getObject returns an incorrect timestamp (timezone offset?)

Seems to me getObjects('WikiPage',(id=>1)) should return the same as getObject('WikiPage',1)
but that ain't happening.

**Comment by adam-buckley** [comment]
Can you post the data that it's returning please?

**Comment by syntithenai** [comment]
ta for the explanation on the new way to set timezone

**Comment by adam-buckley** [comment]
For anyone wondering, you now set your timezone using ```Config::set("system.timezone");``` in your project config.
