### ISSUE TITLE
protect user admin update username against population

### ISSUE THREAD

**Issue by syntithenai** [2pisoftware/cmfive#185]
I am normally logged into cmfive using auth details admin/admin

When I create a new user, login as them and edit their profile, the form is autopopulated with the admin user details from the browser form autofill.

So if I'm not watching, I end up updating the username to admin (which shouldn't be possible either)

**Comment by adam-buckley** [comment]
This is a [Chrome issue only](http://stackoverflow.com/questions/15738259/disabling-chrome-autofill) apparently. I've had this issue in the past and the fix is not elegant at all...

**Comment by adam-buckley** [comment]
I think the latest version of Chrome finally fixes this issue, i.e. no longer prefilling: 
![screen shot 2016-02-29 at 4 43 55 pm](https://cloud.githubusercontent.com/assets/1585392/13386731/b6c2bbba-df03-11e5-8cee-19e422f25a0a.png)
