### ISSUE TITLE
Lookup for Action templates should not look deep

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive#190]
Currently templates for actions are looked up using Web::fetchTemplate() which looks in a variety of places starting with the most specific and if it can't find it there going upwards to the most generic. 

This is the current function doc:

``` php
     * /<moduledir>/<module>/templates/<submodule>/<action>_<httpmethod>.tpl.php
     * /<moduledir>/<module>/templates/<submodule>/<action>.tpl.php
     * /<moduledir>/<module>/templates/<submodule>/<submodule>.tpl.php
     * /<moduledir>/<module>/templates/<action>_<httpmethod>.tpl.php
     * /<moduledir>/<module>/templates/<action>.tpl.php
     * /<moduledir>/<module>/templates/<module>.tpl.php
     * /<moduledir>/<module>/<action>_<httpmethod>.tpl.php
     * /<moduledir>/<module>/<action>.tpl.php
     * /<moduledir>/<module>/<module>.tpl.php
     * /<templatedir>/<action>_<httpmethod>.tpl.php
     * /<templatedir>/<action>.tpl.php
     * /<templatedir>/<module>.tpl.php
```

This is great for looking up layout templates because it gives the option of overriding the default layout at any point. However it is NOT desirable for looking up action templates.

Please change the way web looks up action templates so that only the following paths are searched:

``` php
     * /<moduledir>/<module>/templates/<submodule>/<action>_<httpmethod>.tpl.php
     * /<moduledir>/<module>/templates/<submodule>/<action>.tpl.php
```

**Comment by syntithenai** [comment]
So  stop searching in the templatedir and limit it to these options ?

     * /<moduledir>/<module>/templates/<submodule>/<action>_<httpmethod>.tpl.php
     * /<moduledir>/<module>/templates/<submodule>/<action>.tpl.php
     * /<moduledir>/<module>/templates/<submodule>/<submodule>.tpl.php
     * /<moduledir>/<module>/templates/<action>_<httpmethod>.tpl.php
     * /<moduledir>/<module>/templates/<action>.tpl.php
     * /<moduledir>/<module>/templates/<module>.tpl.php
     * /<moduledir>/<module>/<action>_<httpmethod>.tpl.php
     * /<moduledir>/<module>/<action>.tpl.php
     * /<moduledir>/<module>/<module>.tpl.php

Steve


On Wed, Mar 2, 2016 at 9:33 AM, Carsten Eckelmann <notifications@github.com>
wrote:

> Currently templates for actions are looked up using Web::fetchTemplate()
> which looks in a variety of places starting with the most specific and if
> it can't find it there going upwards to the most generic.
>
> This is the current function doc:
>
>      * /<moduledir>/<module>/templates/<submodule>/<action>_<httpmethod>.tpl.php     * /<moduledir>/<module>/templates/<submodule>/<action>.tpl.php     * /<moduledir>/<module>/templates/<submodule>/<submodule>.tpl.php     * /<moduledir>/<module>/templates/<action>_<httpmethod>.tpl.php     * /<moduledir>/<module>/templates/<action>.tpl.php     * /<moduledir>/<module>/templates/<module>.tpl.php     * /<moduledir>/<module>/<action>_<httpmethod>.tpl.php     * /<moduledir>/<module>/<action>.tpl.php     * /<moduledir>/<module>/<module>.tpl.php     * /<templatedir>/<action>_<httpmethod>.tpl.php     * /<templatedir>/<action>.tpl.php     * /<templatedir>/<module>.tpl.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2pisoftware/cmfive/issues/190>.
>



-- 
Steve Ryan
Software Engineer
stever@syntithenai.com
phone (mobile) 0423 083 685
phone (SIP)  61262237142
skype : irishflute
260 Spring Creek Road Buckajo NSW 2550
Australia

**Comment by careck** [comment]
Sorry Steve, I have updated my initial comment after realising that I clicked save too early.
