### ISSUE TITLE
Move Composer directories up into top level

### ISSUE THREAD

**Issue by careck** [2pisoftware/cmfive#191]
Currently the composer directories are located in /system. This works fine until you have a user module which tries to add composer dependencies. User modules (top level modules) should never ever change or add files in /system, so the way how we merge system and user composer dependencies is flawed.

By moving the /composer directory tree to the top level we solve this problem. Also then /system can be used for many installations where /system is included as symlink.

**Comment by adam-buckley** [comment]
While the composer directory is gitignored and won't really affect anything, I agree that the composer directory should be in the project root as that is generally standard practice.
