### ISSUE TITLE
Create audit archival feature

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive#195]
I've seen the audit table amass over 230 million rows of log entries. We need an audit archival feature, however, if this the excess audit entries are causing HDD space issues though, archiving will most likely fail. I think an archive, in conjunction with a relaxation of what we audit is a good combination.

**Comment by careck** [comment]
The archival process could export the audit entries to a csv file, which gets zipped and stored to the attachment folder. If this attachment folder is on S3 (using the filesystem layer) then there is no problem with space.

**Comment by adam-buckley** [comment]
That's a big if! Cmfive users shouldn't have to sign up to S3 to guarantee that Cmfive won't obliterate their hard drive space!

**Comment by adam-buckley** [comment]
This is currently implemented on the feature/OmitFromSearch branch, needs testing but it will get in eventually. The CSV is given to the user to download and do what they want with the audit table entries
