### ISSUE TITLE
Working with PHP7

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive#227]
At the moment, the Creole wiki parser is throwing a heap of E_DEPRECATED errors in PHP7, that's because the developer used the name of the class as the constructor. Since Creole hasn't been updated in 5+ years, I would recommend forking the project and updating it ourselves.

At the moment, we can hide errors by setting the error_reporting flags in the index.php file:
```php
error_reporting(E_ALL & ~E_DEPRECATED);
```

But this is what it looks like when you don't:
![screenshot_2016-11-11_06-54-30](https://cloud.githubusercontent.com/assets/1585392/20191961/f6deaea6-a7db-11e6-95d8-f1023828ecee.png)

**Comment by careck** [comment]
This seems to be an abandoned code base and we should just make the changes on our copy.

**Comment by adam-buckley** [comment]
Fixed Creole library in b5f6dec1e2515518686414bcf4d754a5d601ce5d, will leave this issue open for any other PHP7 issues
