### ISSUE TITLE
Add logs everywhere.

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive#89]
Logs are awesome, we need more of them, adding logs everywhere will give us an idea in the long run of how the system is used. Monolog seems to also have extensions to monitor the server itself which would be pretty awesome!

With monolog, its also easy to add extra parameters such as the current logged in user etc. so we can do that too.

**Comment by careck** [comment]
closed because not this issue doesn't describe a clear achievable outcome.
