### ISSUE TITLE
Changes pages with external tab links to buttons

### ISSUE THREAD

**Issue by adam-buckley** [2pisoftware/cmfive#99]
At the moment, there is no ability to link to another page from a tab head, as there was with the previous tab implementation.

I.e., when a tab head element is clicked, the system only sends anything after the hash ("#comments" for example) to the changeTab function (in main.js). Meaning only anything expressed as an anchor (or the anchor of a complete URL) is used to switch tabs, anything else is ignored.

The main reason for above is the fact that tabs are only there for switching the appearance of the tab body divs _internally_, so linking to another page doesn't really make sense from a UX point of view. If we want to link to another page, then I suggest just adding a link somewhere else.

However, if it becomes that we want to be able to link to other pages via a tab head, I will strongly disagree using the point described above, then eventually cave in and do it :)

**Comment by careck** [comment]
I think that was all done ... please open new SPECIFIC tickets for any case where we missed this.
